envVarGroups:
- name: evg-nochange-envVars
  envVars:
  - key: STABLE_KEY
    value: stable-value
  - key: REMOVABLE_KEY
    value: removable-value
- name: evg-remove-envVars
  envVars:
  - key: STABLE_KEY
    value: stable-value
  - key: REMOVABLE_KEY
    value: removable-value
- name: evg-add-envVars
  envVars:
  - key: STABLE_KEY
    value: stable-value
  - key: REMOVABLE_KEY
    value: removable-value
