services:
# A Docker web service
- type: web
  name: fixed
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  numInstances: 3
- type: web
  name: autoscaling
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  scaling:
    minInstances: 2
    maxInstances: 10
    targetCPUPercent: 70
- type: web
  name: previews
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  previews:
    numInstances: 5
- type: web
  name: fixed-previews
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  numInstances: 3
  previews:
    numInstances: 5
- type: web
  name: autoscaling-previews
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  previews:
    numInstances: 5
  scaling:
    minInstances: 2
    maxInstances: 10
    targetCPUPercent: 70
- type: web
  name: fixed-autoscaling
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  numInstances: 3
  scaling:
    minInstances: 2
    maxInstances: 10
    targetCPUPercent: 70
- type: web
  name: fixed-autoscaling-previews
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  numInstances: 3
  previews:
    numInstances: 5
  scaling:
    minInstances: 2
    maxInstances: 10
    targetCPUPercent: 70
