---
services:
- name: image-to-native
  type: web
  runtime: node
  repo: https://github.com/render-examples/express-hello-world
  buildCommand: yarn install --frozen-lockfile
  startCommand: node app.js
  envVars:
  - key: NODE_ENV
    value: production
- name: native-to-image
  type: web
  runtime: image
  image:
    url: docker.io/library/nginx:latest
